version: '3.8'

services:
  portfolio-react:
    build: 
      context: .
      dockerfile: Dockerfile.dev
    working_dir: /app
    volumes:
      - .:/app
      - /app/node_modules
    ports:
      - "3000:3000"
    command: yarn dev
    environment:
      - CHOKIDAR_USEPOLLING=true