name: Deploy Portfolio
 
on:
  workflow_dispatch:
  push:
    branches:
      - main
#teste
jobs:
  build-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v1
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }}

      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@v1
        with:
          project_id: ${{ secrets.GCP_PROJECT }}

      - name: Configure Docker to use gcloud as credential helper
        run: gcloud auth configure-docker $GCP_REGION-docker.pkg.dev
        env:
          GCP_REGION: ${{ secrets.GCP_REGION }}

      - name: Debug env vars
        run: |
          echo "GCP_PROJECT: $GCP_PROJECT"
          echo "GCP_REGION: $GCP_REGION"
        env:
          GCP_PROJECT: ${{ secrets.GCP_PROJECT }}
          GCP_REGION: ${{ secrets.GCP_REGION }}

      - name: Build Docker image
        run: docker build -t $GCP_REGION-docker.pkg.dev/$GCP_PROJECT/portfolio-repo/my-portfolio:latest -f dockerfile.prod .
        env:
          GCP_PROJECT: ${{ secrets.GCP_PROJECT }}
          GCP_REGION: ${{ secrets.GCP_REGION }}

      - name: Push Docker image
        run: docker push $GCP_REGION-docker.pkg.dev/$GCP_PROJECT/portfolio-repo/my-portfolio:latest
        env:
          GCP_PROJECT: ${{ secrets.GCP_PROJECT }}
          GCP_REGION: ${{ secrets.GCP_REGION }}

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2

      - name: Terraform Init
        working-directory: ./terraform
        run: terraform init

      - name: Terraform Apply
        working-directory: ./terraform
        run: terraform apply -auto-approve
